# Generated by Django 4.1.3 on 2022-11-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.melbournefoodandwine.com.au/image-tools.php?w=560&h=440&src=/recipes/recipe-placeholder.jpg', max_length=500),
        ),
    ]
